### ISSUE TITLE
Window button issues on Firefox 107

### ISSUE THREAD

**Issue by ArtyIF** [rafaelmardojai/firefox-gnome-theme#501] opened 2022-11-26 07:07 UTC
See screenshot. Usability is not affected, it's purely a visual bug

![image](https://user-images.githubusercontent.com/8017858/204076760-81c2d6a9-51cb-4f99-b30f-67994fcca10c.png)

Using FGT 107 (1b658e15bb61e98d862c21c336cecbc934e1c422)

**Comment by ArtyIF** [comment] 2022-11-26 07:08
Also I just noticed that when hovering, the close button turns red. AFAIK no Libadwaita app does that.
![image](https://user-images.githubusercontent.com/8017858/204076840-506b8aa6-f428-4e3f-9395-2e0f8176777a.png)

**Comment by rafaelmardojai** [comment] 2022-12-16 18:13
I cant reproduce this. Could you give more info about you setup?

**Comment by baptiste0928** [comment] 2022-12-16 21:08
I can reproduce this on Firefox 108.1 (Flatpak version on Fedora 37) with latest theme version (5468312cc2647cedb3c0ad3ae677442da00d7993).

**Comment by ArtyIF** [comment] 2022-12-16 21:30
I've been able to reproduce this since I updated to 1b658e15bb61e98d862c21c336cecbc934e1c422 and later version, on Firefox 106 and 107. Currently using 107.0.1, and it's still there, as well as #492 which stayed closed despite me confirming it's reproducible in the version of Firefox that FGT commit was made for.

**Comment by rafaelmardojai** [comment] 2022-12-16 21:36
Are you using `gnomeTheme.systemIcons` or something? That's the only thing I can think that could cause this.

**Comment by ryan-griffin** [comment] 2022-12-17 02:57
I can reproduce this issue on firefox 108, except I don't have a red close button, only dimmed minimize and maximize/restore icons. However when I use `gnomeTheme.systemIcons` all icons become dimmed.

**Comment by baptiste0928** [comment] 2022-12-17 12:15
I can reproduce both dimmed icons and red close button without `gnomeTheme.systemIcons`. It looks like the dimmed style is the one that is active when the window is unfocused, and for some reason, minimize and maximize icons always have this style.

**Comment by ArtyIF** [comment] 2022-12-17 20:41
My `gnomeTheme.systemIcons` is not set, so I assume it's false

**Comment by rafaelmardojai** [comment] 2022-12-18 03:35
Enabled maximize and minimize buttons and was able to reproduce the dimmed icons issue. Should be fixed now.

But the red button remains a mystery.

**Comment by ArtyIF** [comment] 2022-12-18 09:13
I found out what caused the red button issue. I had a theme set to "Dark" in Firefox, and not to "System theme — auto".

**Comment by ArtyIF** [comment] 2022-12-18 09:15
Also, since I removed FGT to see if the stock Dark theme does that and then installed it again, that fixed the buttons disappearing issue. Weird.

**Comment by ArtyIF** [comment] 2022-12-18 10:08
> Also, since I removed FGT to see if the stock Dark theme does that and then installed it again, that fixed the buttons disappearing issue. Weird.

Nevermind, the buttons disappearing issue is back. Weird.

**Comment by rafaelmardojai** [comment] 2022-12-18 13:41
> Nevermind, the buttons disappearing issue is back. Weird.

What do you mean with buttons disappearing? The dimmed icons bug showed in your first screenshot should be fixed by 
5212b0fd8be7309ba32db3d1e4763a11e05dd60c.

@ryan-griffin @baptiste0928 could you confirm?

**Comment by rafaelmardojai** [comment] 2022-12-18 13:43
> I found out what caused the red button issue. I had a theme set to "Dark" in Firefox, and not to "System theme — auto".

This is stated in the README:

> Also though is not obligatory, some weird issues might happen if you don't use the Firefox's default/system theme because the theme is never tested against the Firefox's light or dark theme.

**Comment by rafaelmardojai** [comment] 2022-12-18 13:49
> See #492. Despite it being closed, it's still there

I see, then I will close this issue as the dimmed icons are fixed and the red button is clarified.

Will reopen the other issue, though I can't reproduce it, so I wouldn't be able to solve it for now.

**Closed by rafaelmardojai** 2022-12-18 13:49 UTC
Labels: unconfirmed

**Comment by ryan-griffin** [comment] 2022-12-18 18:21
> > > Nevermind, the buttons disappearing issue is back. Weird.
> > 
> > 
> > What do you mean with buttons disappearing? The dimmed icons bug showed in your first screenshot should be fixed by [5212b0f](https://github.com/rafaelmardojai/firefox-gnome-theme/commit/5212b0fd8be7309ba32db3d1e4763a11e05dd60c).
> > @ryan-griffin @baptiste0928 could you confirm?
> 
> See #492. Despite it being closed, it's still there

Its fixed for me.
