### ISSUE TITLE
Menu has no paddings in Firefox 91

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#267] opened 2021-08-18 09:24 UTC
Just updated to new Firefox 91 and menu stopped to have paddings:

![Снимок экрана от 2021-08-18 11-23-52](https://user-images.githubusercontent.com/19343/129873550-46144d61-a07d-434b-a32b-9377d8148af1.png)

(Thanks for the amazing theme)

**Comment by rafaelmardojai** [comment] 2021-08-18 13:14
Duplicate of #249. It's fixed in `beta` branch. I will try to merge it today.

**Closed by rafaelmardojai** 2021-08-18 13:14 UTC
