### ISSUE TITLE
The right-click menu does not show the icon, how do I deal with it?

### ISSUE THREAD

**Issue by DrZhang1208** [rafaelmardojai/firefox-gnome-theme#589] opened 2023-04-08 04:08 UTC
The right-click menu does not show the icon, how do I deal with it?
![图片](https://user-images.githubusercontent.com/97793620/230702516-75a74a1b-ff4c-4b40-ab4f-8eec3eeca3a6.png)

**Comment by rafaelmardojai** [comment] 2023-04-10 16:46
I can't reproduce this on Firefox 111. Could you give some more info about your setup?

**Comment by DrZhang1208** [comment] 2023-04-11 02:40
It may have been caused by my version being too high. In version 112, there is also a situation where the close button of the window overlaps with other buttons. By trying, I have solved it by removing some css code, thank you very much for the excellent code.
![图片](https://user-images.githubusercontent.com/97793620/231041245-173db9b1-7701-4236-915a-4c597cbf3e24.png)
The above picture shows that the window close button and the menu button overlapped, but after my attempts, it has been solved.
![图片](https://user-images.githubusercontent.com/97793620/231041435-c9e54505-aa65-477e-ad77-a2726e555184.png)

![图片](https://user-images.githubusercontent.com/97793620/231041296-53558c3e-4f41-4db9-b247-88c090a93405.png)
The right-click menu is also, after my attempts, has been solved.
![图片](https://user-images.githubusercontent.com/97793620/231041556-42fb5d13-375a-4e44-a0a8-7997f4a46c09.png)

Thank you again for the excellent theme!

**Comment by DrZhang1208** [comment] 2023-04-12 05:09
I solved the problem by removing the following code.

https://user-images.githubusercontent.com/97793620/231355680-68edf451-9ee7-42b2-bd37-670b4b1811b9.mp4


The window button in the upper right corner is solved by adjusting the offset of the control button next to it.

**Comment by DrZhang1208** [comment] 2023-04-12 05:28
Yes, I'm using windows. Although this theme is not made for windows, I'm pleased to be able to make it work in windows with a simple modification.

**Comment by rafaelmardojai** [comment] 2023-04-12 12:19
@DrZhang1208 If you want, would be nice if you share your findings to make it work with Windows on our Github discussions: https://github.com/rafaelmardojai/firefox-gnome-theme/discussions.

Also probably I would accept patches using some Windows only media query like:

```css
@media (-moz-os-version: windows-win7),
       (-moz-os-version: windows-win8),
       (-moz-os-version: windows-win10) {
  /* Code */
}
```
To add Windows support fixes, but that will require someone to commit to maintain that code.

PD: I'm closing this issue since isn't affecting Linux and therefore I cant fix it.

**Closed by rafaelmardojai** 2023-04-12 12:19 UTC
Labels: bug, unconfirmed
