### ISSUE TITLE
Headerbar hides website content when in fullscreen and `browser.fullscreen.autohide` equals false

### ISSUE THREAD

**Issue by rien333** [rafaelmardojai/firefox-gnome-theme#746] opened 2024-01-13 20:18 UTC
**Describe the bug**
I believe the fix for https://github.com/rafaelmardojai/firefox-gnome-theme/issues/677 may have caused a bit of a regression: now, when `browser.fullscreen.autohide` is set to false (which is not its default value), the top part of websites becomes completely inaccessible, since it's being hidden behind the headerbar. This can be quite annoying, as websites populate their top part with important content. 
 
I'm not sure if "regression" is the appropriate term, though, as  `bowser.fullscreen.autohide` needs to be set to a non-default value for this bug to occur.

My gut feeling is that https://github.com/rafaelmardojai/firefox-gnome-theme/commit/6aca7418bfbf8bbe0669a742d8d92919dc33db61 could be the culprit, as (1) it relates to overlaying the headerbar on top of website content, and (2) because I do not recall this undesirable behavior being present before v121.1 (maybe @rafaelmardojai can speak to this?) 

**To Reproduce**

1. Set `browser.fullscreen.autohide` to false 
2. Create a fullscreen firefox window
3. Certain website elements, such as the github "Issues", "Pull Requests" tabs, will be permanently hidden beneath the headerbar 

**Expected behavior**
Website content should never be inaccessible due to being hidden beneath UI elements. 

**Setup information**
 - OS: Arch Linux
 - Installation method: AUR
 - Firefox version: 121.0.1
 - Theme version: 121.1
 - Optional features enabled:  `gnomeTheme.HideSingleTab`

**Comment by rafaelmardojai** [comment] 2024-01-15 01:30
Yeah, we want to respect the Firefox preferences. Wrapping b80b75d0a7bec302295f446e1f2febae464d9af7 with `@media (-moz-bool-pref: "browser.fullscreen.autohide")` should fix that.

This change was introduced on `v121`.

> Certain website elements, such as the github "Issues", "Pull Requests" tabs, will be permanently hidden beneath the headerbar

This only happens when you move the mouse to the top to make the toolbar appear right? If the toolbar stays after you stop hovering the toolbar, then we have a bug, although I can't reproduce it.

**Comment by rafaelmardojai** [comment] 2024-01-15 01:30
It should be fixed by eb7c43d11abc157f97d032018115c9f7b04ca4de.

**Closed by rafaelmardojai** 2024-01-15 01:30 UTC
Labels: bug
