### ISSUE TITLE
Download indicator is not appearing (icon is transparent)

### ISSUE THREAD

**Issue by hrqmonteiro** [rafaelmardojai/firefox-gnome-theme#597] opened 2023-04-16 11:53 UTC
**Describe the bug**
Download button is not appearing/transparent

**To Reproduce**
Just seeing the download button

**Expected behavior**
Not to be transparent?

**Screenshots**
[Screencast from 2023-04-16 08-52-15.webm](https://user-images.githubusercontent.com/17055027/232308014-e8dd4e6c-5d6c-4776-9959-0705455553b0.webm)

**Setup information**
 - OS: Fedora 37
 - Installation method: script
 - Firefox version: 112.0
 - Theme version: latest
 - Optional features enabled: none

**Additional context**
N/A

**Comment by rafaelmardojai** [comment] 2023-04-16 13:15
Duplicate of #594.

**Closed** 2023-04-16 13:16 UTC
Labels: bug

**Comment by rafaelmardojai** [comment] 2023-04-16 13:17
This should be fixed already.  Please make sure you're running the latest version, and if the issue persist comment on the other issue.
