### ISSUE TITLE
"List all tabs" button is invisible

### ISSUE THREAD

**Issue by pedrofleck** [rafaelmardojai/firefox-gnome-theme#44] opened 2019-07-17 05:22 UTC
The icon to list all tabs is missing when using Adwaita icons provided by the theme. I installed using the install script and the "-g" option. It looks like [this](https://i.imgur.com/y9H5EPk.png).

**Comment by rafaelmardojai** [comment] 2019-07-17 13:43
Caused by hack for scrollbars to work. Now should be fixed.

**Closed** 2019-07-17 13:43 UTC

**Comment by rafaelmardojai** [comment] 2019-07-17 13:45
Note: this doesn't happen in Nightly 70.

**Comment by pedrofleck** [comment] 2019-07-17 16:05
Just tested here and it's indeed fixed. Thanks!
