### ISSUE TITLE
A few weird issues with menus

### ISSUE THREAD

**Issue by folknor** [rafaelmardojai/firefox-gnome-theme#249] opened 2021-06-07 19:48 UTC
Hi!

I'm terribly sorry if this is because I'm running firefox nightly, or perhaps one of my addons, but there's a few issues with menus that I'd like to present for your consideration.

In the application menu itself there seems to be a lot of padding/margin missing;
![appmenu](https://user-images.githubusercontent.com/233791/121078719-d3755200-c7c8-11eb-9bcb-135e409d97a2.png)

And in the context menu there appears to be two "frames" around it, and also the colors are slightly different but that might be intended;
![contextmenu](https://user-images.githubusercontent.com/233791/121078824-f0aa2080-c7c8-11eb-85ca-85a74dbed1fd.png)

Thank you for the excellent work. I love it, and I've been using it since the first release :-)

**Comment by rafaelmardojai** [comment] 2021-06-07 20:18
I can't reproduce, so it's probably a nightly thing.

**Comment by folknor** [comment] 2021-06-07 20:46
Okay, thank you.

**Comment by rafaelmardojai** [comment] 2021-06-07 21:34
Let's keep it open, I need to checkout it.

**Comment by folknor** [comment] 2021-07-26 20:30
If I remove this rule it looks a bit better https://github.com/rafaelmardojai/firefox-gnome-theme/blob/master/theme/parts/popups.css#L118

Are you still not seeing this?

**Comment by rafaelmardojai** [comment] 2021-07-26 23:41
I just have installed FF91, I'm going to push the fixes to `beta` branch.

**Comment by rafaelmardojai** [comment] 2021-07-27 00:16
Should be fixed in the `beta` branch.

**Closed** 2021-07-27 00:17 UTC

**Comment by folknor** [comment] 2021-07-27 13:37
Apologies, I forgot that nightly is essentially two releases ahead. It was not my intention to push you in any way.

Thanks a lot for everything, it looks perfect now with the beta branch.

**Comment by rafaelmardojai** [comment] 2021-07-27 14:10
No problem, the issues now were also in Firefox beta, and I usually try to fix things on beta when possible :)

**Comment by folknor** [comment] 2021-08-01 08:04
There's a few things that I forgot to mention earlier, I wasn't sure if you wanted a new ticket for them or not. They might also be in beta only, I'm not sure.

1. Text in update button is misaligned both vertically and horizontally
![firefox-update-button](https://user-images.githubusercontent.com/233791/127763972-c487a686-1a03-4871-9561-aa19bf2abaaa.png)


2. Hover effect is different in context menus (page, tab, toolbar, etc) and application menus (hamburger and traditional File menulist)
![firefox-hover-mainmenu](https://user-images.githubusercontent.com/233791/127763977-ca42030f-25fc-40a0-bd2d-ab3499360b23.png)
![firefox-hover-context](https://user-images.githubusercontent.com/233791/127763978-58645305-7272-4479-8453-5d7712c92ccd.png)

**Comment by rafaelmardojai** [comment] 2021-08-03 04:59
> There's a few things that I forgot to mention earlier, I wasn't sure if you wanted a new ticket for them or not. They might also be in beta only, I'm not sure.

No problem.

> Hover effect is different in context menus (page, tab, toolbar, etc) and application menus (hamburger and traditional File menulist)

That's how Adwaita looks, context menus vs popovers. And the theme always have looked like that. Or what do you mean with "hover effect"?

**Comment by JaneSmith** [comment] 2021-08-28 07:07
Was the Bookmarks menu missed in this update? I can confirm that the main menu (hamburger menu button), the Library menu, and the History menu have decent padding around the border, but the Bookmarks menu seems to miss this. The Bookmarks menu is very cramped, and the arrow at the top doesn't look right.

Here is a screenshot of what I'm seeing: https://i.imgur.com/1b1DhNa.png

**Comment by ai** [comment] 2021-08-28 11:24
I created another issue about Bookmarks menu issue https://github.com/rafaelmardojai/firefox-gnome-theme/issues/269

**Comment by rafaelmardojai** [comment] 2021-08-28 13:21
@JaneSmith Yeah, the Bookmarks menu is a "weird" poppup, and always need specific fixes and I forgot about that.

**Comment by folknor** [comment] 2021-08-28 14:27
> That's how Adwaita looks, context menus vs popovers. And the theme always have looked like that. Or what do you mean with "hover effect"?

Indeed. I had never noticed :-P Thank you!

The issue with the blue "Update available" button in the popover (first screenshot in https://github.com/rafaelmardojai/firefox-gnome-theme/issues/249#issuecomment-890471555) is still there.

**Comment by JaneSmith** [comment] 2021-08-28 17:15
Okay, it's good to know you're aware of it. I did see that other issue but as that was talking about the Bookmarks sidebar, rather than the Bookmarks menu, I didn't think it was related. Sorry for pestering.

Thanks for all your hard work on this. I've been using it for a long time and it's really fantastic for making Firefox fit in better.
