### ISSUE TITLE
[BUG] Doesn't follow system theme (dark and light)

### ISSUE THREAD

**Issue by hrqmonteiro** [rafaelmardojai/firefox-gnome-theme#524] opened 2022-12-17 17:59 UTC
**Describe the bug**
Doesn't follow system settings for dark and light.

**Expected behavior**

**Screenshots**
[Screencast from 2022-12-17 14-59-08.webm](https://user-images.githubusercontent.com/17055027/208255147-a36aacb4-0b92-4407-aa58-2ba0bd5fb406.webm)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser Firefox
 - Version 108

**Comment by rafaelmardojai** [comment] 2022-12-18 03:16
I can't reproduce this. Works fine for me. (Fedora 37, Firefox 108 flatpak)

**Comment by yursan9** [comment] 2022-12-18 11:48
I can reproduce this: 
[Screencast from 2022-12-18 18-47-06.webm](https://user-images.githubusercontent.com/17114559/208296667-0f209338-0f74-4704-84a9-11d5b1dd461b.webm)

- OS: Fedora 37
- Browser: Firefox 108

**Comment by rafaelmardojai** [comment] 2022-12-18 12:09
Could you confirm if it also happens with vanilla Firefox? We're just using media queries here.

**Comment by rafaelmardojai** [comment] 2022-12-18 13:45
Another question, by any chance are you using the Firefox dark or light theme? This will only work if you have the system theme enabled.

**Comment by emansom** [comment] 2022-12-18 15:52
Install the Night Theme Switcher GNOME extension and configure that to switch the legacy GTK themes as well.

**Comment by rafaelmardojai** [comment] 2022-12-18 16:36
> Install the [Night Theme Switcher GNOME extension](https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension), and configure that to switch the legacy GTK themes to Adw and Adw-dark (special GTK4+ and GTK3+ cross-compatible Adwaita theme, generated from [adw-gtk3](https://github.com/lassekongo83/adw-gtk3) and Adwaita) from [this AUR package](https://aur.archlinux.org/packages/adw-gtk-theme).

Any way, Firefox supports the global color scheme setting when the system theme is enabled, so shouldn't be needed.

**Comment by yursan9** [comment] 2022-12-19 01:40
I used the system theme:
![image](https://user-images.githubusercontent.com/17114559/208328018-6fbc8627-eb75-4780-9ead-b3dd97ca3e3c.png)
Let me try starting firefox inside troubleshoot mode

**Comment by yursan9** [comment] 2022-12-19 01:42
Ok I still reproduce this issue inside troubleshoot mode.
Can I assume this is firefox bug?

**Comment by yursan9** [comment] 2022-12-19 02:07
I think I found the culprit. If you set Dark GTK3 theme as legacy application theme inside Gnome Tweak, Light/Dark mode will not work for application still using GTK3. The solution is to set the light theme as default legacy application theme.

**Comment by rafaelmardojai** [comment] 2022-12-19 02:13
> I think I found the culprit. If you set Dark GTK3 theme as legacy application theme inside Gnome Tweak, Light/Dark mode will not work for application still using GTK3. The solution is to set the light theme as default legacy application theme.

Right, if you're changing your GTK3 theme, then I would recommend your to use the @emansom workaround.

**Comment by rafaelmardojai** [comment] 2022-12-23 18:22
I'm closing this since isn't the theme's fault.

**Closed by rafaelmardojai** 2022-12-23 18:22 UTC
