### ISSUE TITLE
Firefox 110.0 (64-bit): gnomeTheme.hideSingleTab doesn't work 

### ISSUE THREAD

**Issue by wroyca** [rafaelmardojai/firefox-gnome-theme#562] opened 2023-02-20 20:26 UTC
## Description:
The gnomeTheme.hideSingleTab setting in Firefox 110.0 (64-bit) is not working as intended. Even when the setting is set to true, the single tab is still visible in the browser window.

Steps to reproduce:

    Open Firefox 110.0 (64-bit) on a Linux system with the GNOME desktop environment.
    Type "about:config" in the address bar and press Enter.
    Search for "gnomeTheme.hideSingleTab" and set it to "true".
    Restart Firefox.
    Open a new tab in Firefox.
    Close all other tabs except the new one.

## Expected result:
The single tab should be hidden, as the gnomeTheme.hideSingleTab setting is set to "true".

## Actual result:
The single tab is still visible, even though the gnomeTheme.hideSingleTab setting is set to "true".

![image](https://user-images.githubusercontent.com/91024200/220192435-85de6663-04f7-4e73-9548-beee18770276.png)

**Comment by ferlanero** [comment] 2023-02-20 20:55
I can confirm this bug on Firefox 110.0 (64-bit) on Ubuntu (.deb) and ArchLinux installs

**Comment by rafaelmardojai** [comment] 2023-02-20 21:16
This looks like a duplicated of #552, already fixed on master branch. What version of the theme are you running?

**Comment by ferlanero** [comment] 2023-02-20 21:21
> This looks like a duplicated of #552, already fixed on master branch. What version of the theme are you running?

What do you mean with "Version of the theme?"

I have performed a one command curled script but tabs area always present even if there is only one

**Comment by rafaelmardojai** [comment] 2023-02-20 21:27
> > This looks like a duplicated of #552, already fixed on master branch. What version of the theme are you running?
> 
> What do you mean with "Version of the theme?"
> 
> I have performed a one command curled script install but tabs area always present even if there is only one

Right, the curled script installs the latest "tagged/stable" release, so you will need to wait until I'm able to tag a new version this week. Otherwise you can follow the other installation methods to use the theme master branch.

**Comment by rafaelmardojai** [comment] 2023-02-20 21:27
Anyway, I'm closing this since indeed it's a duplicated.

**Closed by rafaelmardojai** 2023-02-20 21:27 UTC
Labels: bug
