### ISSUE TITLE
Most elements in toolbar after exiting fullscreen with FGT 107

### ISSUE THREAD

**Issue by ArtyIF** [rafaelmardojai/firefox-gnome-theme#492] opened 2022-11-19 19:35 UTC
Sometimes (not sure when, I assume after YouTube fullscreen) most elements in the toolbar go missing outside of the three buttons on the side of the toolbar. The only way to fix this is to open the Customize Toolbar tab and close it.

Expected:
![image](https://user-images.githubusercontent.com/8017858/202868285-2faec11c-82b4-4e9d-88f5-527b8d750e1b.png)

Actual:
![image](https://user-images.githubusercontent.com/8017858/202868516-b3e0a12d-ddbe-43f4-9347-9e2c5bb51c1f.png)

Using commit f259ce1844ee714bdceabce9524808d5ef1b8301, FIrefox 106.0.4

**Comment by ArtyIF** [comment] 2022-11-19 19:41
Attached screenshot. Apparently it's also doing it right side first, then left side? Also it's inconsistent, when I decided to report the bug the new tab button was also missing.

**Comment by ArtyIF** [comment] 2022-11-19 19:41
UPD: I went out of YouTube fullscreen again and the new tab button is gone now
![image](https://user-images.githubusercontent.com/8017858/202868577-233577b1-5543-4df2-aec4-0dbe439f0eb4.png)

**Comment by CleoMenezesJr** [comment] 2022-11-20 01:25
There are changes in Firefox 107 that caused several bugs in Firefox GNOME Theme. We are sending commits to fix these bugs.
It would be interesting if you use release 106 (I would like to know if this bug is also replicated in this release).

**Comment by CleoMenezesJr** [comment] 2022-11-20 01:26
There are changes in Firefox 107 that caused several bugs in Firefox GNOME Theme. We are sending commits to fix these bugs on master branch.
It would be interesting if you use the release 106 (I would like to know if this bug is also replicated in this release).

**Comment by ArtyIF** [comment] 2022-11-20 08:03
> There are changes in Firefox 107 that caused several bugs in Firefox GNOME Theme. We are sending commits to fix these bugs on master branch. It would be interesting if you use the release 106 (I would like to know if this bug is also replicated in this release).

![image](https://user-images.githubusercontent.com/8017858/202891894-743522ed-79c9-40bc-8dc9-2a44c62426a5.png)
I am using 106. Or do you mean GNOME Theme v106?

**Comment by ArtyIF** [comment] 2022-11-20 08:16
Okay, downgraded to tags/v106, the bug seems to be solved on Firefox 106. I can't test it with Firefox 107 unfortunately

**Comment by rafaelmardojai** [comment] 2022-11-21 02:42
> Okay, downgraded to tags/v106, the bug seems to be solved on Firefox 106.

Yes, `master` branch usually have fixes for the current stable Firefox version (107 right now), and sometimes those fixes can break older versions because we don't have the time to maintain backward compatibility. So yeah, using a stable tag is the right thing to do if aren't updating your Firefox soon.

**Comment by ArtyIF** [comment] 2022-11-26 09:16
Issue still persists in Firefox 107 with the master version. Reopen the issue please
![image](https://user-images.githubusercontent.com/8017858/204081483-a38306ef-72a4-421a-9fcb-2b775c8bc199.png)

**Comment by ArtyIF** [comment] 2022-12-18 14:01
It randomly also doesn't happen, but it starts happening again on restart. Also I assume it needs to be a video on something like YouTube to reproduce the bug.

**Comment by rafaelmardojai** [comment] 2022-12-19 04:48
Ok, after a lot of playing I was able to reproduce this. Looks like some of the navbar items just disappear from the DOM tree. So I'm assuming it might be a Firefox bug.

**Comment by rafaelmardojai** [comment] 2022-12-19 05:00
So looks like the missing buttons are moved to the overflow menu. This means that we are some how triggering the Firefox system for when there is no enough room in the toolbar.

**Comment by ArtyIF** [comment] 2022-12-19 19:27
This started happening between FGT 106 and 107. Unfortunately, due to breaking changes in Firefox 108, I can't test where exactly, but this should narrow it down a bit.

**Comment by rafaelmardojai** [comment] 2022-12-20 18:12
Well, now that I want to test if reverting some of those changes fix the problem, I can't reproduce it again, looks like it's a very inconsistent bug.

**Comment by Protrikk** [comment] 2022-12-22 20:21
Happens to me on 108.0.1

**Comment by rafaelmardojai** [comment] 2022-12-23 14:04
I'm suspecting of the urlbar animation that was also animating its width. I have pushed a fix to master, could you test if that solves the issue? I can't reproduce this since some days, so can't say.

**Comment by Protrikk** [comment] 2022-12-23 15:14
Seems like it fixed it for me

**Comment by rafaelmardojai** [comment] 2022-12-23 16:41
@ArtyIF could you confirm?

**Comment by ArtyIF** [comment] 2022-12-23 17:10
Can confirm, it's fixed now

**Comment by rafaelmardojai** [comment] 2022-12-23 18:20
Thanks, closing then.

**Closed by rafaelmardojai** 2022-12-23 18:20 UTC
Labels: bug, upstream
