### ISSUE TITLE
Firefox 133 Breakages

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#849] opened 2024-10-30 02:59 UTC
In an effort to make it a little less annoying for you I'm going to combine issues here that were introduced with the new Firefox 133 beta 1 with example screenshots below each issue. If it's more annoying this way let me know and I'll make them seperate issues next time! As always thank you for the time you put in to this project c:

1) The close button is completely invisible now
![Screenshot From 2024-10-30 02-57-58](https://github.com/user-attachments/assets/a2d85ad1-226d-4e03-a97d-076498a9cf9e)

2) Highlight selection is slightly off in bookmarks menu now for bookmarks with longer titles
![Screenshot From 2024-10-30 02-58-45](https://github.com/user-attachments/assets/32dbe2d0-1ae7-4243-989f-05363f966282)

3) Search bar and results only look okay if you squint your eyes really, really hard
![Screenshot From 2024-10-30 03-01-55](https://github.com/user-attachments/assets/6b343b52-fa1f-485d-ac11-b3426780aabb)

**Comment by rafaelmardojai** [comment] 2024-10-30 03:07
> The close button is completely invisible now

Already fixed in the `nightly` branch for some time.

 > Search bar and results only look okay if you squint your eyes really, really hard

I can't reproduce this, maybe I haven't got the update for that change yet.

**Comment by KUPOinyourWINDOW** [comment] 2024-10-30 03:20
I'm running the current beta branch of the theme as version 133 has just hit beta, should I try the nightly branch and see if if they're fixed there?

**Comment by rafaelmardojai** [comment] 2024-10-30 13:56
All issues should be addressed in the `beta` branch.

**Comment by KUPOinyourWINDOW** [comment] 2024-10-31 00:06
can confirm, every one has been fixed, thank you!

**Comment by bertin0** [comment] 2024-11-26 18:14
firefox 133 has become stable, (it's in the arch repos now too), we should merge the changes into main.

**Comment by ak-42** [comment] 2024-11-26 18:53
Firefox is now on v133 on Flathub too

**Closed** 2024-11-27 01:29 UTC
Labels: bug, nightly/beta

**Comment by rafaelmardojai** [comment] 2024-11-27 01:31
> for me, tabsAsHeaderbar is broken on firefox 133 stable 

@bertin0 Please open a new issue for that.
