### ISSUE TITLE
Tabs are sometimes stuck

### ISSUE THREAD

**Issue by SeaDve** [rafaelmardojai/firefox-gnome-theme#176] opened 2020-11-17 14:36 UTC
There are times which I can't rearrange the tabs within the tab bar, they are fixed on that position and order. However, by restarting the browser, it is back to normal.

**Comment by rafaelmardojai** [comment] 2020-11-18 20:12
Interesting, I have never experienced that.

More info about your setup? Wayland? Firefox version?
A screencast of the bug would be useful also.

**Comment by SeaDve** [comment] 2020-11-19 01:23
My setup is:
 - Fedora 33 Workstation 
 - Wayland
 - Firefox 82.0.3

I will try to screencast it if the bug reappears as it has only happened to me rarely (only twice so far).

**Comment by SeaDve** [comment] 2020-11-21 05:07
I was able to replicate the bug by dragging a tab to the hot corner in GNOME, here's how the bug looks like:

![1605932405549-min](https://user-images.githubusercontent.com/64297935/99868073-3ff87d00-2bfa-11eb-967e-5387a45f8e17.gif)

In the video I was trying to rearrange/move the tabs. It's not working until I restarted firefox.

**Comment by rafaelmardojai** [comment] 2020-11-21 18:05
Have you tested if drag and drop stops only in tabs or in general? 

Also it could be a Firefox/wayland bug, could you try to reproduce it without the theme?

**Comment by SeaDve** [comment] 2020-11-22 00:19
I was able to reproduce it without the theme. So it is an upstream bug?

**Comment by rafaelmardojai** [comment] 2020-11-22 01:13
> I was able to reproduce it without the theme. So it is an upstream bug?

Yes, and probably a wayland related one.

**Comment by rafaelmardojai** [comment] 2020-11-22 01:48
Searching a bit, it could be a mutter issue, see:

https://bugzilla.redhat.com/show_bug.cgi?id=1647457

https://gitlab.gnome.org/GNOME/mutter/-/issues/740

**Comment by rafaelmardojai** [comment] 2020-11-22 01:49
Closing since we can't do anything here.

**Closed by rafaelmardojai** 2020-11-22 01:49 UTC
Labels: bug
