### ISSUE TITLE
White line between url and tabs when loosing window focus

### ISSUE THREAD

**Issue by tymmesyde** [rafaelmardojai/firefox-gnome-theme#570] opened 2023-03-19 07:11 UTC
**Describe the bug**
A white line appears between the url and tabs when loosing the window focus with dark theme set

**To Reproduce**
Blur / unfocus window; by pressing Alt / Tab for example

**Expected behavior**
The white line should not appear

**Screenshots**
Focused
![image](https://user-images.githubusercontent.com/7889816/226159454-f4ca2905-865e-4683-bfb1-e235fa427143.png)
Unfocused
![image](https://user-images.githubusercontent.com/7889816/226159437-2fd1d82b-6081-4699-885d-563285592aee.png)

**Setup information**
 - OS: Fedora
 - Installation method: install-by-curl script
 - Firefox version: 110
 - Theme version: 110
 - Optional features enabled: None

**Additional context**

**Comment by lolwuz** [comment] 2023-03-21 01:15
This was a sore in my eyes as well.

 In the file: /theme/colors/dark.css
Change 

```
/* Header bar */
    --gnome-headerbar-background: #303030;
    --gnome-headerbar-border-color: var(--gnome-toolbar-border-color);
    --gnome-inactive-headerbar-background: var(
      --gnome-browser-before-load-background
    );
    **--gnome-inactive-headerbar-border-color: var(
      --gnome-inactive-toolbar-border-color
    );**
```

To:

```
/* Header bar */
    --gnome-headerbar-background: #303030;
    --gnome-headerbar-border-color: var(--gnome-toolbar-border-color);
    --gnome-inactive-headerbar-background: var(
      --gnome-browser-before-load-background
    );
    **--gnome-inactive-headerbar-border-color: rgba(0, 0, 0, 0.36);**
```

I don't know much about css variables, it looks correct to me but something is going wrong here.

**Comment by tymmesyde** [comment] 2023-03-21 03:25
> This was a sore in my eyes as well.
> 
> In the file: /theme/colors/dark.css Change
> 
> ```
> /* Header bar */
>     --gnome-headerbar-background: #303030;
>     --gnome-headerbar-border-color: var(--gnome-toolbar-border-color);
>     --gnome-inactive-headerbar-background: var(
>       --gnome-browser-before-load-background
>     );
>     --gnome-inactive-headerbar-border-color: var(
>       --gnome-inactive-toolbar-border-color
>     );
> ```
> 
> To:
> 
> ```
> /* Header bar */
>     --gnome-headerbar-background: #303030;
>     --gnome-headerbar-border-color: var(--gnome-toolbar-border-color);
>     --gnome-inactive-headerbar-background: var(
>       --gnome-browser-before-load-background
>     );
>     --gnome-inactive-headerbar-border-color: rgba(0, 0, 0, 0.36);
> ```
> 
> I don't know much about css variables, it looks correct to me but something is going wrong here.

Thanks it worked !
I honestly don't understand what's happening with this variable i tried multiple things to fix this issue but failed

**Comment by rafaelmardojai** [comment] 2023-03-26 23:16
Sadly I still can't reproduce this.

**Comment by Titaniumtown** [comment] 2023-03-27 05:45
I cannot reproduce this either

**Comment by lolwuz** [comment] 2023-03-27 21:03
Ubuntu 23.04, Firefox 111.0.1
But I had this issue since Ubuntu 22.10

Looks like it is a issue with the css variable scope. Did some digging but I can't pin the issue right now. 

Changing 

```
--gnome-inactive-headerbar-border-color: var(
      --gnome-inactive-toolbar-border-color
    );
```

To this:

```
 --gnome-inactive-headerbar-border-color: var(
      --gnome-toolbar-border-color
   );
```

Also fixes the issue.

**Comment by rafaelmardojai** [comment] 2023-04-11 23:48
@lolwuz I still can't reproduce but I have committed your suggestion.

**Closed** 2023-04-11 23:48 UTC
Labels: bug, unconfirmed
