### ISSUE TITLE
firefox 108 breaks everything

### ISSUE THREAD

**Issue by OldWorldOrdr** [rafaelmardojai/firefox-gnome-theme#510] opened 2022-12-13 20:40 UTC
![Screenshot from 2022-12-13 15-31-20](https://user-images.githubusercontent.com/57970114/207437565-6e19ba67-da11-42ab-a538-4f3483b349fd.png)

**Comment by JayceFayne** [comment] 2022-12-13 20:49
Duplicate of #504

**Closed** 2022-12-13 21:44 UTC
