### ISSUE TITLE
Closing Button Hover Shape

### ISSUE THREAD

**Issue by fweth** [rafaelmardojai/firefox-gnome-theme#98] opened 2019-11-18 07:22 UTC
The shape around the window closing button, which becomes visible when hovering, changed in some recent GNOME version (I think 3.34) from round cornered square to circle, but it's still round cornered square in this theme.

**Comment by rafaelmardojai** [comment] 2019-11-18 13:34
Right now you need to enable the `rounded-title-buttons.css` optional feature: https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features

**Comment by rafaelmardojai** [comment] 2019-11-18 13:40
Duplicate of #77

**Closed by rafaelmardojai** 2019-11-18 13:40 UTC
Labels: duplicate

**Comment by fweth** [comment] 2019-11-18 19:34
Sorry for not having done my own research and thanks for the quick reaction!
