### ISSUE TITLE
Strange Tab Highlight in Firefox Beta (119)

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#678] opened 2023-10-04 07:51 UTC
There's an odd highlight effect on tabs in the new Firefox Beta, it appears that half of an active tab is highlighted, half isn't and in private windows half has the title bar colour, half doesn't. Tricky to explain so I'll attach screenshots below and hopefully you'll see what I mean.

Active but not highlighted by the mouse cursor:
![Screenshot from 2023-10-04 08-45-54](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/8de79496-f676-4d93-9cad-9dd846831fac)

Active but this time highlighted by the mouse cursor:
![Screenshot from 2023-10-04 08-48-16](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/d316f35f-b648-453f-b962-dd90c7ccd943)

Active but not highlighted in Incognito Mode:
![Screenshot from 2023-10-04 08-49-39](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/c7a5fa8a-15bd-4433-9e0c-72495f373094)

Active but highlighted by the mouse cursor in Incognito Mode:
![Screenshot from 2023-10-04 08-50-41](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/a57fa60d-1826-483c-93ec-229fa23cdf38)

**Comment by rafaelmardojai** [comment] 2023-10-04 12:30
It should be fixed in the theme's beta branch, can you test it?

**Comment by KUPOinyourWINDOW** [comment] 2023-10-05 06:15
It is indeed pretty much fixed, its still slightly visible for a second during the tab highlight animation but its very subtle, when the animation isn't happening though it is completely fixed

**Comment by cewbdex** [comment] 2023-10-05 17:10
I do not know if this is a different or same issue, but when I select more tabs:
![obrazek](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/9021297/54c0955e-76da-497f-a05a-97845c0878ce)

**Comment by rafaelmardojai** [comment] 2023-10-05 18:14
> I do not know if this is a different or same issue, but when I select more tabs:
> ![obrazek](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/9021297/54c0955e-76da-497f-a05a-97845c0878ce)
> 

Different issue caused by the same close button overlay. Honestly it has been there forever, but I never cared to fix it 😅, feel free to create a new issue for it.

**Closed** 2023-10-25 16:53 UTC
Labels: bug
