### ISSUE TITLE
Layout got broken

### ISSUE THREAD

**Issue by kerelape** [rafaelmardojai/firefox-gnome-theme#511] opened 2022-12-14 05:20 UTC
This is what happened to my firefox after a reboot (I did not do anything to my system).

![image](https://user-images.githubusercontent.com/92184297/207511163-c33294f0-6ab5-4671-a357-33d1cf7cf215.png)

More details:
- Tabs do not show up (but still available via Ctrl+TAB)
- App menu button overlaps window control buttons
- Search bar is too small
- Toolbar button fills the whole title bar of the window (overlapping search and forward/backward buttons, but the reload button is still clickable)

Ubuntu 22.10 (amd64), X11, Gnome 43

<del>I won't be able to provide you with any further information because I am reinstalling the theme</del>
Edit: reinstalling (by removing "chrome" directory and installing again following README) does not fix it

**Comment by DumbledoreCalrissian** [comment] 2022-12-14 09:13
I too have the same problem on Firefox 108. Waiting for a fix. _/\_

**Comment by sheeepdev** [comment] 2022-12-14 09:33
Duplicate of #504

**Closed** 2022-12-14 13:45 UTC
