### ISSUE TITLE
Theme breaks "Firefox Multi-Account Containers" extension popup

### ISSUE THREAD

**Issue by ghost** [rafaelmardojai/firefox-gnome-theme#92] opened 2019-11-06 13:40 UTC
https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/ is a first-party extension by Mozilla and one of the AMO-Recommended extensions. It has 220+k users.

Unfortunately, with this theme, the popup for this extension is completely broken, with text being displayed gray on gray apparently.

**Comment by georgelemental** [comment] 2019-11-16 23:12
It looks perfectly normal on my machine.

**Comment by sknorr** [comment] 2019-11-18 16:00
I just reinstalled and it still ![looks like this](https://user-images.githubusercontent.com/5476547/69068303-d103a980-0a24-11ea-9392-70b612bc3b2e.png).

**Comment by Slomo17** [comment] 2019-12-03 14:46
I have the problem, that the download pop up is not always showing when clicking it, sometimes it works sometimes the popup doens't shows up at all, i couldn't figure out when it happens, yet. I don't know if this is related to the this bug. Multi-Account Container however works for me.

**Comment by maymage** [comment] 2019-12-11 12:48
@Slomo17 
This might be a different bug. I experience the same, but only on wayland, not on xorg. You may check that..

**Comment by Slomo17** [comment] 2019-12-12 08:21
Yes i experienced it on wayland, can't check it on xorg any more, since i updated to firefox 71, here it works but the popups are unthemed as already repored here [#91 ](https://github.com/rafaelmardojai/firefox-gnome-theme/issues/91)

**Comment by fbruetting** [comment] 2020-02-23 15:22
This is how it looks for me. It’s inverted but fully usable.

![Bildschirmfoto von 2020-02-23 16-20-36](https://user-images.githubusercontent.com/10520767/75114698-a430e500-5658-11ea-92d6-3b9b988079aa.png)

**Comment by sknorr** [comment] 2020-02-24 11:02
Still seems broken for me, now that all the popovers are themed again (@ 119baa1).

**Comment by Slomo17** [comment] 2020-02-28 11:34
Still don't know if this is related, but i also experience problems with the download button/menu again sometimes, now that it is themed again. But here the problem is, that the popup doesn't show at all. Couldn't figure out yet, when the problems occur, somtimes is works as supposed, sometimes it's broken.

**Comment by gitSaptarshi** [comment] 2020-08-09 18:18
@rafaelmardojai It has happened to my system. Look at the screenshot below.

![Screenshot from 2020-08-09 23-39-46](https://user-images.githubusercontent.com/37685073/89738903-e2508280-da99-11ea-9045-7f4e47141b28.png)
As you can all see the texts in the highlighted option is clearly not readable.

### System specification
- OS: Fedora Rawhide
- GNOME version: 3.37.3
- Windowing system: X11
- Firefox version: 78.0.2 (64-bit)

I just installed the theme today (_Sun, 9 Aug 2020_) after performing all system updates.
PS: don't know the situation at Wayland side.

**Comment by rafaelmardojai** [comment] 2020-08-12 02:30
@gitSaptarshi I wasn't able to reproduce it. 

Firefox 78.0.2 / Fedora 31 and Firefox 79 Flatpak, both under X11.

**Comment by gitSaptarshi** [comment] 2020-08-17 16:06
My system is Fedora Rawhide (prereleased development version of fedora). I guess it my OS is at fault here.

**Comment by gitSaptarshi** [comment] 2020-08-17 16:14
I have done manual installation btw. The installation script did not work for me for the wrong symlinks which you have already noticed. You have already nalied the looks of firefox to be considered as the default web browser of choice in many GNOME based distros. Hope you can fix this annoying issue. Keep up the awesome work.

**Comment by CleoMenezesJr** [comment] 2022-11-19 01:31
I will close this issue not only because it is old, but also because in the current version (107) I tried to reproduce and apparently everything is fine.

**Closed by CleoMenezesJr** 2022-11-19 01:31 UTC
Labels: bug
