### ISSUE TITLE
Firefox 132 Mute Button is UNHOLY

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#837] opened 2024-10-02 02:50 UTC
Exorcise this button please
![Screenshot From 2024-10-02 03-49-11](https://github.com/user-attachments/assets/de0f0de2-c2f1-4823-985c-9a3c6048a309)

**Comment by rien333** [comment] 2024-10-02 11:37
Can't reproduce, please provide more information about your installation (firefox version, firefox-gnome-theme-version, OS/distro, etc.)

**Comment by KUPOinyourWINDOW** [comment] 2024-10-02 11:40
Firefox 132 beta 1, Flatpak, Fedora 41, Gnome 47,
every tab that plays media has this cursed mute button because Firefox has updated the mute button visuals

**Comment by rien333** [comment] 2024-10-02 11:42
Sorry, I'm stupid and confused 132 with 131 for a second. My bad. Guess said info can still be helpful 🙂

**Comment by rafaelmardojai** [comment] 2024-10-03 22:43
Fixed in `beta` branch.

**Comment by KUPOinyourWINDOW** [comment] 2024-10-03 23:03
Can confirm, its fixed! Thank you as always, love the theme and appreciate your work, will continue to report beta bugs as they come to help!

**Comment by rien333** [comment] 2024-10-30 10:05
FIY, this was release today, and the mute buttons indeed look unholy. Thanks for your work!

**Closed** 2024-10-30 12:54 UTC
Labels: bug, nightly/beta

**Comment by iaacornus** [comment] 2024-10-30 18:12
for some reason, the problem still persists in my firefox despite of update, ff132, silverblue 41
