### ISSUE TITLE
TabsAsHeaderbar enabled after update even if not toggled

### ISSUE THREAD

**Issue by winkelnp** [rafaelmardojai/firefox-gnome-theme#626] opened 2023-05-11 14:03 UTC
**Describe the bug**

After update to 113 `tabsAsHeaderbar` is functions as if enabled even if toggled off in about:config

**To Reproduce**

1. Update to 113 (I think I saw it in the beta version before as well)
2. Check about:config

**Expected behavior**

Tabs remain not in the Headerbar.

**Setup information**
 - OS:  Fedora 38
 - Installation method:  git
 - Firefox version:  113
 - Theme version:  master
 - Optional features enabled:  gnomeTheme.dragWindowHeaderbarButtons, gnomeTheme.hideWebrtcIndicator

**Comment by rafaelmardojai** [comment] 2023-05-11 14:19
You sure you're running the latest version? This is already fixed.

And this has nothing to do with tabsAsHeaderbar, it's just that the reordering code stoped working.

**Comment by rafaelmardojai** [comment] 2023-05-11 14:21
Also duplicate of #568.

**Closed** 2023-05-11 14:21 UTC
Labels: duplicate
