### ISSUE TITLE
Search bar has extra space in bottom

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#441] opened 2022-09-24 12:23 UTC
![image](https://user-images.githubusercontent.com/62639087/192097714-bba7c74c-70ec-43bc-85c7-ca36055580d6.png)

Nightly 107

**Comment by CleoMenezesJr** [comment] 2022-09-27 02:36
I can't reproduce. BTW, this search bar seems completely broken. Did you make any local change?

Have you tested to update the theme with `git pull`?

**Comment by bbhtt** [comment] 2022-09-27 11:40
> I can't reproduce. 

Are you on Nightly? I mentioned that this happens with Nightly 107. 

> Did you make any local change?

No

> Have you tested to update the theme with git pull?

I'm on the latest commit 53e54cc12e54408b54d2562d903e3441ee0a4021

**Comment by CleoMenezesJr** [comment] 2022-11-17 18:30
@bbhtt, I'm using version 107, and now I can confirm the existence of the problem. I already fixed that. I'll go over a few more things, but by today it should be fixed.
Thanks to report this!

**Closed** 2022-11-18 02:31 UTC
Labels: nightly/beta

**Comment by bbhtt** [comment] 2022-11-18 04:28
> @bbhtt, I'm using version 107, and now I can confirm the existence of the problem. I already fixed that. I'll go over a few more things, but by today it should be fixed. Thanks to report this!

Thanks!
