### ISSUE TITLE
Improve private window distinction 

### ISSUE THREAD

**Issue by ispanos** [rafaelmardojai/firefox-gnome-theme#147] opened 2020-07-08 09:56 UTC
I don't know if there is an indicator that a window is private or not, but since I didn't notice it yet, maybe it could be more clear.

**Comment by rafaelmardojai** [comment] 2020-07-08 16:39
There's an indicator on headerbar, similar to GNOME Web. But is hard to see on small windows.

![Captura de pantalla de 2020-07-08 11-32-19](https://user-images.githubusercontent.com/6210397/86945509-b8104b80-c10e-11ea-97c4-f4ec67af41d0.png)

A better approach could be to tint the headerbar like GNOME Web. Probably using purple, since blue sucks a bit.

**Comment by ispanos** [comment] 2020-07-08 16:55
What's going on in your screenshot? Where are the tabs? Having so little vertical space taken from the tab bar looks so nice.

I created a new profile and I saw what you mean. On my profile I have removed the spacing around the address bar, so I couldn't see anything. 
![20200708-194838](https://user-images.githubusercontent.com/42875202/86947286-3f33e280-c154-11ea-9f78-08b1a36ff078.png)
The button on the top right isn't an indicator, it just opens a Private window.

**Comment by rafaelmardojai** [comment] 2020-07-08 17:05
I have enable `hide-single-tab.css` optional feature (https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features). You need to remove all buttons from tabsbar.

I think i will try the purple headerbar tinting to improve this.

**Comment by ispanos** [comment] 2020-07-08 21:17
I enabled the hide-single-tab.css. THANK YOU SO MUCH!!!!!
I've been looking for a way to do minimize vertical space for so long!
I had this repo in my bookmarks for about a year and I never tried it before.

**Comment by rafaelmardojai** [comment] 2020-07-09 22:30
Current progress. Working on light version first.

![Captura de pantalla de 2020-07-09 17-27-17](https://user-images.githubusercontent.com/6210397/87096931-91830b00-c209-11ea-9d80-2ee6138daf8c.png)

**Comment by ispanos** [comment] 2020-07-09 22:35
This looks more like pink to me than purple, but that color change is definitely sufficient. I'm not a light theme user, so I don't know if that color fits the rest of the theme.

**Comment by rafaelmardojai** [comment] 2020-07-09 22:39
> This looks more like pink to me than purple

Yeah, I know. The problem is I need a color that plays well with Adwaita's light gray.
Dark version will be more purple.

**Comment by rafaelmardojai** [comment] 2020-07-10 01:23
A preview of dark variant:
![Captura de pantalla de 2020-07-09 20-04-42](https://user-images.githubusercontent.com/6210397/87105832-a4a1d500-c221-11ea-8d8f-a4911c84ff1a.png)

**Comment by rafaelmardojai** [comment] 2020-07-11 00:58
Landed on master! Please test.

![Captura de pantalla de 2020-07-10 19-57-27](https://user-images.githubusercontent.com/6210397/87213053-9d44ff00-c2e7-11ea-8ad7-f3cd0c147c4f.png)

![Captura de pantalla de 2020-07-10 19-40-26](https://user-images.githubusercontent.com/6210397/87212996-42130c80-c2e7-11ea-96cc-6840cfa6b688.png)

**Comment by ispanos** [comment] 2020-07-11 01:12
I like the purple accent you choose. My OCD is annoying me because you didn't use `#8B1EAC`, as seen in the icon bellow, but I like the colours you choose.
![20200711-040935](https://user-images.githubusercontent.com/42875202/87213264-6a712a00-c32c-11ea-86f6-641c2db58bd0.png)

Only issue, is the 3rd to last icon on the top right. It's the "Open an new private browsing window' shortcut. The icon isn't visible at all. I only tested the dark theme.

![20200711-040758](https://user-images.githubusercontent.com/42875202/87213220-241bcb00-c32c-11ea-82bf-ca8db994b0c8.png)

![20200711-040806](https://user-images.githubusercontent.com/42875202/87213223-2847e880-c32c-11ea-8e4a-c8b3afeda1f4.png)

**Comment by rafaelmardojai** [comment] 2020-07-11 02:40
> I like the purple accent you choose. My OCD is annoying me because you didn't use #8B1EAC, as seen in the icon bellow, but I like the colours you choose.

LOL, Yeah sorry. But I wanted to use the purple from GNOME color palette. 

> Only issue, is the 3rd to last icon on the top right. It's the "Open an new private browsing window' shortcut. The icon isn't visible at all. I only tested the dark theme.

Related to daaf6f01e7e362db3183614e4160251324657fb2. Fixing now.

**Comment by rafaelmardojai** [comment] 2020-07-11 02:43
> Related to daaf6f0. Fixing now.

Fixed in 99df8a5a1cecec4235055205180959b9114952f0!

**Closed** 2020-07-11 13:14 UTC
Labels: enhancement
