### ISSUE TITLE
Misalignment of menu name text inside hamburger menu

### ISSUE THREAD

**Issue by Nakamerica** [rafaelmardojai/firefox-gnome-theme#566] opened 2023-03-08 21:21 UTC
**Describe the bug**
The menu names (such as 'History', 'Bookmarks', 'More Tools', etc) inside the hamburger menu panel are misaligned as shown in the screen snips below. This exists on all the panels mentioned above as well as the panel inside these panels themselves. 

**To Reproduce**
1. Go to the hamburger menu
2. Click on 'History', 'Bookmarks', 'More Tools', 'Help', 'Recently closed tabs', 'Recently closed windows', etc 
3. See the misalignment

**Expected behavior**
Aligned text

**Screenshots**
![Screenshot from 2023-03-09 02-38-22](https://user-images.githubusercontent.com/88226614/223852222-2318989e-1166-4029-8f7c-ecb5906d2988.png)
![Screenshot from 2023-03-09 02-38-31](https://user-images.githubusercontent.com/88226614/223852247-b6ae7060-3c08-432f-a546-fe30c2d7dbf8.png)
![Screenshot from 2023-03-09 02-38-49](https://user-images.githubusercontent.com/88226614/223852379-a352aa0b-4336-4993-a2f2-75d651e89742.png)
![Screenshot from 2023-03-09 02-38-57](https://user-images.githubusercontent.com/88226614/223852425-7d3d2950-489d-4077-88ec-e305ac156020.png)

**Setup information**
 - OS: Fedora 37 Workstation edition (GNOME Wayland)
 - Installation method: installation script
 - Firefox version: 110.0
 - Theme version: latest at the time of issue creation
 - Optional features enabled: None
 
**Additional context**
None

**Comment by rafaelmardojai** [comment] 2023-03-12 00:46
Hmm, I know this was an issue but should be fixed since [7ca750214e8b4ae460e9782e4e402206cf2a59be], you sure that are you running the latest version? If so, then I can't reproduce it.

**Closed** 2023-04-11 23:43 UTC
Labels: bug, unconfirmed

**Comment by Nakamerica** [comment] 2023-07-05 17:35
I am now using the master branch and the issue is fixed, thanks.
