### ISSUE TITLE
auto-install.sh replaces user.js if it already exists

### ISSUE THREAD

**Issue by proninyaroslav** [rafaelmardojai/firefox-gnome-theme#478] opened 2022-11-08 14:18 UTC
I use a custom user.js to disable telemetry and other stuff like that and when I install the Firefox Gnome theme, it replaces user.js (it asks for this before replacing). I think the script's strategy should be like this: create a new one if it doesn't exist, or append own data to the end of an existing file without erasing user data.

**Comment by ArtyIF** [comment] 2022-11-26 07:04
For me, on Fedora 37, auto-install.sh always asks to replace user.js. I also use Flatpak version of Black Box and oh-my-zsh, if it may contribute to that.

![image](https://user-images.githubusercontent.com/8017858/204076707-cde8702f-7c39-4167-b04a-e467238f4880.png)

**Comment by alosarjos** [comment] 2022-12-20 13:07
I also get asked and even if said no still replaces it

**Comment by alosarjos** [comment] 2022-12-20 13:12
I see the issue. the question is provided when recreating the symbolic link of user.js, but the real file is being overwritten anyways, maybe I can check it and fix it.

**Comment by rafaelmardojai** [comment] 2022-12-20 14:16
> I also get asked and even if said no still replaces it

The issue here is about not replacing the file but appending the contents so previous user settings are conserved.

I the script is replacing the file when you said no, then it's a bug and should be fixed. 

We are just running this: `ln -is chrome/firefox-gnome-theme/configuration/user.js user.js`.

**Comment by alosarjos** [comment] 2022-12-20 14:21
The thing is. If the user has let's say a clean install without the theme, and a custom user.js, the script will behave as expected, and will override the file only of the user accepts to replace the file.

The real issue here I think, is that, if I install the theme, then edit the user.js (Which is a symlink to the real file inside /configuration/user.js) to add more rules, and then run the autoinstaller to update the theme. the real user.js inside configuration is replaced and then, it asks if you want to replace the symlink. But since the real file has been replaced by the `cp -fR "$THEMEDIRECTORY" "$PWD"` all that config is lost.

**Comment by alosarjos** [comment] 2022-12-20 14:25
So the situations when running the script can be:

1. Clean install, no `user.js` exists
2. `user.js` exists, and user is asked to replace it with a symlink to the one of the theme
3. Theme is already installed, `user.js` is a symlink of the theme

On the first and second cases it's all good right now, the issue is the third one.

I think that the best option could be not using a symlink at all on this, if the file doesn't exists, copy it, if it exists check missing lines from the theme and append to it.

I can give it a look if you want.

**Comment by rafaelmardojai** [comment] 2022-12-20 14:38
To be honest the third option was never considered nor supported (modifying the config file inside the theme).

The symlink approach was used because in the early days users installed the theme one time and then used git to update, so this was the better way to get new settings added without manually checking if the file changed. I know that some users are still using this approach.

But I'm definitely open to changes that can improve the situation.

**Comment by alosarjos** [comment] 2022-12-20 16:13
I guess the ideal situation would be:

Check if user.js exists:
 - If it doesn't, create symlink
 - If it does:
   - If content is = theme user.js, do nothing
   - If content is different, append existing content to real user.js and replace with symlink. Also check if previous content has the theme config lines to avoid somehow duplicated lines

I'm not an expert on bash scripting but may give it a try if no one else wants and if you see it as a valid plan

**Comment by rafaelmardojai** [comment] 2022-12-20 16:52
@alosarjos Sounds like a good approach. Feel free to work on it.

I don't know if @TriplEight would be interested on helping with this.

**Comment by bbhtt** [comment] 2023-03-31 03:16
I use this locally https://github.com/bbhtt/firefox-gnome-theme/commit/42ba4aed6f0368423486f203e7599a2f4042a916

My solution is drop the symlinking and always append the prefs to profile user.js

If `user.js` does not exist in profile folder I move the one from theme.

If it exists I read the prefs from theme user.js into two arrays. The first array contains the formatted pref ie. `user_pref("arg", val)` to append and the next array has just the pref key ie. `arg`. Then I  delete the entire lines matching `arg` from profile user.js to unset any set values of pref. Then I append the formatted prefs from first array to profile user.js.

Please let me know if this works or if I missed any cases.

**Comment by rafaelmardojai** [comment] 2023-03-31 12:28
@bbhtt Looks good for me!

I think it covers all what we want. Feel free to open a PR.

**Closed** 2023-04-04 22:44 UTC
Labels: enhancement, help wanted
